// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBciL3OMq17Q6YtNNqbujJt1yDBSmcgmnY',
    appId: '1:744430224562:web:45f315f3d277f3d76535ab',
    messagingSenderId: '744430224562',
    projectId: 'mmm-project-9de44',
    authDomain: 'mmm-project-9de44.firebaseapp.com',
    storageBucket: 'mmm-project-9de44.firebasestorage.app',
    measurementId: 'G-T8X5K043D0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZC0rs2WeSVQ4Gw8CkjsFLsLkldj5QHuo',
    appId: '1:744430224562:android:79f25431087892f46535ab',
    messagingSenderId: '744430224562',
    projectId: 'mmm-project-9de44',
    storageBucket: 'mmm-project-9de44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_4R2lFR7GKuop7VfGE2OhMYX8C-2zpBQ',
    appId: '1:744430224562:ios:6ba9d04f0c13489b6535ab',
    messagingSenderId: '744430224562',
    projectId: 'mmm-project-9de44',
    storageBucket: 'mmm-project-9de44.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_4R2lFR7GKuop7VfGE2OhMYX8C-2zpBQ',
    appId: '1:744430224562:ios:6ba9d04f0c13489b6535ab',
    messagingSenderId: '744430224562',
    projectId: 'mmm-project-9de44',
    storageBucket: 'mmm-project-9de44.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBciL3OMq17Q6YtNNqbujJt1yDBSmcgmnY',
    appId: '1:744430224562:web:4483a55b75e16d5b6535ab',
    messagingSenderId: '744430224562',
    projectId: 'mmm-project-9de44',
    authDomain: 'mmm-project-9de44.firebaseapp.com',
    storageBucket: 'mmm-project-9de44.firebasestorage.app',
    measurementId: 'G-RZQ6N5ZDMD',
  );
}
